version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/pandeo/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/pandeo/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
       - WP_DB_LOGIN_A=${WP_DB_LOGIN}
       - WP_DB_PASSWORD_A=${WP_DB_PASSWORD}
       - WP_DB_PASSWORD_ROOT_A=${WP_DB_PASSWORD_ROOT}
       - WP_DB_NAME_A=${WP_DB_NAME}
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
       - WP_DB_NAME_A=${WP_DB_NAME}
       - WP_DB_LOGIN_A=${WP_DB_LOGIN}
       - WP_DB_PASSWORD_A=${WP_DB_PASSWORD}
       - WP_DB_HOST_A=${WP_DB_HOST}
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
