version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/pandeo/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/pandeo/data/mariadb
  mc:
    driver: local
    name: mc
    driver_opts:
      type: none
      o: bind
      device: /home/pandeo/data/minecraft

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
       - WP_DB_LOGIN_A=${WP_DB_LOGIN}
       - WP_DB_PASSWORD_A=${WP_DB_PASSWORD}
       - WP_DB_PASSWORD_ROOT_A=${WP_DB_PASSWORD_ROOT}
       - WP_DB_NAME_A=${WP_DB_NAME}
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
       - WP_RD_HOST_A=${WP_RD_HOST}
       - WP_DB_NAME_A=${WP_DB_NAME}
       - WP_DB_LOGIN_A=${WP_DB_LOGIN}
       - WP_DB_PASSWORD_A=${WP_DB_PASSWORD}
       - WP_DB_HOST_A=${WP_DB_HOST}
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb
    volumes:
      - wp:/var/www/
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
       - WP_URL_A=${WP_URL}
       - WP_PERSO_URL_A=${WP_PERSO_URL}
       - WP_AD_URL_A=${WP_AD_URL}
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/
    networks:
      - app-network
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    build:
      context: ./requirements/minecraft
    ports:
      - "25565:25565"
    volumes:
      - mc:/root/minecraft/
    networks:
      - app-network
    restart: unless-stopped

  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
      args:
       - FTP_USR_A=${FTP_USR}
       - FTP_PWD_A=${FTP_PWD}
    ports:
      - "21:21"
    volumes:
      - wp:/var/www/
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    networks:
      - app-network
    restart: unless-stopped